### ISSUE TITLE
Configure Nextcloud to allow ContainerNursery

### ISSUE THREAD

**Issue by C4ArtZ** [ItsEcholot/ContainerNursery#3]
Container immediately crashes after copying conf.yml.example to conf.yml with the following error:

```
node:internal/process/promises:246

          triggerUncaughtException(err, true /* fromPromise */);

          ^


Error: connect ENOENT /var/run/docker.sock

    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {

  errno: -2,

  code: 'ENOENT',

  syscall: 'connect',

  address: '/var/run/docker.sock'

}
```

Tried with latest (1.0.2), 1.0.1 and dev with and without mounting the config directory as docker volume.

**Comment by ItsEcholot** [comment]
Did you mount your Docker socket into the container with `-v /var/run/docker.sock:/var/run/docker.sock`? This is necessary so that ContainerNursery can actually get the status of your containers and issue the start & stop commands.

**Comment by C4ArtZ** [comment]
I didn't think of that. Nursery can now start and stop the container but the redirect doesn't seem to work. I get stuck on the loading screen. I tried with nextcloud and a clean nginx container.


```
{"level":30,"time":1631269196897,"pid":1,"hostname":"645a36df01f4","container":"nginx","msg":"Stopping container"},
{"level":30,"time":1631269201282,"pid":1,"hostname":"645a36df01f4","container":"nginx","msg":"Starting container"},
{"level":30,"time":1631269181876,"pid":1,"hostname":"645a36df01f4","port":8080,"host":"127.0.0.1","msg":"Proxy placeholder server listening"},
{"level":30,"time":1631269181872,"pid":1,"hostname":"645a36df01f4","port":80,"msg":"Proxy listening"},
{"level":30,"time":1631269181857,"pid":1,"hostname":"645a36df01f4","host":"cloud.example.com","container":"nginx","proxy":{"host":"localhost","port":180},"timeoutSeconds":15,"msg":"Added proxy host"},
{"level":30,"time":1631269181856,"pid":1,"hostname":"645a36df01f4","msg":"(Re)loading hosts, clearing all existing hosts first"}
```

**Comment by ItsEcholot** [comment]
What is your `config.yml` File looking like? And how is your routing? Are you using another reverse proxy in front of ContainerNursery? If so how‘s the config of that reverse proxy?

**Comment by C4ArtZ** [comment]
The chain is as follows:
cloud.c4artz.de -> Cloudflare DNS -> Cloudflare Argo tunnel -> Container Nursery -> nextcloud / nginx container

Container Nursery config
```
proxyHosts:
  - domain: cloud.c4artz.de
    containerName: nginx
    proxyHost: localhost
    proxyPort: 180
    timeoutSeconds: 15
```


cloudflared config
```
tunnel: <tunnelid>
credentials-file: /home/c4artz/.cloudflared/<tunnelid>.json

ingress:
  - hostname: cloud.c4artz.de
    service: http://localhost:80
  - service: http_status:404
```
