### ISSUE TITLE
Multiple domain for same container

### ISSUE THREAD

**Issue by JamesDAdams** [ItsEcholot/ContainerNursery#31]
Hi, 

that would be really good to config multiple domain ex: (i have my internet domain and my local domaine)

Like this :

  - domain: [wiki.domain.com, wiki.app.lan]
    containerName: WikiJS
    proxyHost: 192.168.0.120
    proxyPort: 3000
    timeoutSeconds: 300

**Comment by ItsEcholot** [comment]
Good idea, I implemented a first version of this in the `dev` image tag:
`docker pull ghcr.io/itsecholot/containernursery:dev`

Please try it out and report any bugs you find

**Comment by ItsEcholot** [comment]
To add multiple domains use the YAML syntax for arrays, for example:
```yaml
proxyListeningPort: 80
proxyHosts:
  - domain: 
      - dev.domain.com
      - dev2.domain.com
    containerName:
      - WikiJS
    proxyHost: localhost
    proxyPort: 5800
    timeoutSeconds: 10
    stopOnTimeoutIfCpuUsageBelow: 50
```
