### ISSUE TITLE
Bug transfers files with peertube

### ISSUE THREAD

**Issue by JamesDAdams** [ItsEcholot/ContainerNursery#33]
I try to add Peertube with ContainerNursery, and the video file transfer doesn't work :(

**Comment by ItsEcholot** [comment]
This needs more details, can you provide browser js logs, ContainerNursery logs and a more detailed description of what exactly doesn't work?

**Comment by JamesDAdams** [comment]
Nothing in Containernursery logs,

Config : 

```yml
  - domain: peertube.domaine.com
    containerName: 
      - PeerTube
      - PeerTubeRedis
      - PeerTubePostgres
    proxyHost: 192.168.1.100
    proxyPort: 9000
    timeoutSeconds: 60
```

Chrome logs :
![Capture](https://user-images.githubusercontent.com/20860324/156587177-d1f71f84-e9dd-4828-9c82-a63746bd9f35.PNG)
![Capture2](https://user-images.githubusercontent.com/20860324/156587181-1f4ff104-a174-44a7-baa2-2fbef78b18b7.PNG)
![Captur3](https://user-images.githubusercontent.com/20860324/156587187-a5ea93ac-1b74-4f53-8709-3a3c2acc1bfc.PNG)
