### ISSUE TITLE
Impossible to redirect with Mattermost

### ISSUE THREAD

**Issue by JamesDAdams** [ItsEcholot/ContainerNursery#34]
Hi,

i use mattermost and i'm not redirected, I remain stuck on the loading page of ContainerNursery, and the mattermost container are start (it's work on LAN with ip:port)

Config :
```yml
  - domain: mattermost.domaine.com
    containerName: 
      - Mattermost
      - Mattermost-Mysql
    proxyHost: 192.168.1.100
    proxyPort: 10700
    timeoutSeconds: 60
```

```docker
docker run \
  --name='Mattermost' \
  -v /mattermost/data:/mattermost/data \
  -v /mattermost/logs:/mattermost/logs \
  -v /mattermost/config:/mattermost/config \
  -v /mattermost/plugins:/mattermost/plugins \
  -v /mattermost/client/plugins:/mattermost/client/plugins \
  -e MM_SQLSETTINGS_DATASOURCE='JamesServerUser:password@tcp(Mattermost-Mysql:3306)/mattermostJamesServer?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s' \
  -e APP_HOST='mattermost.domaine.com' \
  -e MM_SQLSETTINGS_DRIVERNAME='mysql' \
  ghcr.io/itsecholot/containernursery:latest


docker run \
  --name='Mattermost-Mysql' \
  -v /mattermost/var/lib/mysql:/var/lib/mysql \
  -e MYSQL_DATABASE='mattermostJamesServer' \
  -e MYSQL_USER='JamesServerUser' \
  -e MYSQL_PASSWORD='password' \
  -e MYSQL_ROOT_PASSWORD='password' \
  mysql
```

![Sans titre](https://user-images.githubusercontent.com/20860324/156590423-a7554522-e585-49a8-9956-23127063b594.png)

![Sans titre](https://user-images.githubusercontent.com/20860324/156590707-75287814-2815-4ff2-b7fc-6b0abbc3f1cf.png)
