### ISSUE TITLE
feature request: label for container name

### ISSUE THREAD

**Issue by webysther** [ItsEcholot/ContainerNursery#44]
Support for label the name that's show in the html page will be nice:

```yml
proxyListeningPort: 80
proxyHosts:
  - domain: game.example.com
    label: Game
    containerName: app-game
    proxyHost: emulatorjs
    proxyPort: 80
    timeoutSeconds: 60
    stopOnTimeoutIfCpuUsageBelow: 10
```
