### ISSUE TITLE
Filebrowser doesnt seem to proxy properly

### ISSUE THREAD

**Issue by apsinghnandha** [ItsEcholot/ContainerNursery#47]
So, container does start but it stays loading. If i refresh config file only then the loading stops and login page appears.  Can you please suggest whats causing this?

<img width="500" alt="Screenshot 2023-08-08 at 3 18 24 PM" src="https://github.com/ItsEcholot/ContainerNursery/assets/6174826/56d5547d-688e-4a92-a0c7-bbc12540248f">

**Configuration:**
```
proxyListeningPort: 80
proxyHosts:
  - domain: xyz
      containerName: filebrowser
      proxyHost: filebrowser
      proxyPort: 8080
      timeoutSeconds: 600
```

**FileBrowser Log**
<img width="415" alt="Screenshot 2023-08-08 at 3 18 37 PM" src="https://github.com/ItsEcholot/ContainerNursery/assets/6174826/d462809c-8b58-448c-84e7-bac235eed7f0">
