### ISSUE TITLE
Issue with numerics in hostnames ?

### ISSUE THREAD

**Issue by accforgithubtest** [ItsEcholot/ContainerNursery#51]
Does ContainerNursery require that there are no numerics in proxyHost in the config.yml file?
I have got this working successfully for multiple containers, however only n8n has the below error message.

```
ERROR [2023-09-07 02:47:43.901 +0000]: Config contains invalid proxyHost object
    proxyHost: {
      "domain": [
        "n8n.local.host"
      ],
      "containerName": [
        "n8n"
      ],
      "proxyHost": "n8n",
      "proxyPort": 7545
    }
```

```
  - domain:
      - n8n.local.host
    containerName:
      - n8n
    proxyHost: n8n
    proxyPort: 7545
  - domain:
      - pihole.local.host
    containerName:
      - pihole
    proxyHost: pihole
    proxyPort: 7985
```

@ItsEcholot - Any comment / suggestions appreciated !
