### ISSUE TITLE
container start but not redirected

### ISSUE THREAD

**Issue by JamesDAdams** [ItsEcholot/ContainerNursery#54]
Hi,

i have a bug with [FilesBrowser ](https://github.com/filebrowser/filebrowser)container the container is started by ContainerNursery but on website i'm not redirected.

My config :

```
proxyHosts:
  - domain: files.jamesserver.fr
    containerName: FileBrowser
    proxyHost: 192.168.0.3
    proxyPort: 80
    timeoutSeconds: 30
```

{"level":20,"time":1697390317163,"pid":1,"hostname":"c3f42585130c","host":"files.domaine.fr","target":{"protocol":"http:","host":"127.0.0.1","port":8080},"headers":{"x-container-nursery-container-name":"FileBrowser"},"msg":"Proxied request"}
{"level":20,"time":1697390317179,"pid":1,"hostname":"c3f42585130c","domain":["files.domaine.fr"],"timeoutSeconds":30,"msg":"Resetting connection timeout"}
{"level":20,"time":1697390317180,"pid":1,"hostname":"c3f42585130c","domain":["files.domaine.fr"],"proxyHost":"192.168.0.3","proxyPort":80,"status":404,"headers":{},"msg":"Checked if target is ready"}
{"level":20,"time":1697390348700,"pid":1,"hostname":"c3f42585130c","domain":["files.domaine.fr"],"timeoutSeconds":30,"msg":"Resetting connection timeout"}
