### ISSUE TITLE
Exanmple NPM config and compose

### ISSUE THREAD

**Issue by GamerClassN7** [ItsEcholot/ContainerNursery#59]
hello,
i am trying to setup [ContainerNursery](https://github.com/ItsEcholot/ContainerNursery) but i was not able to setup it correctly with NPM can anyone help me  ?

My configs are following and only think i get is 502 Bad Gateway.
```yaml
version: "3.8"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
      # Uncomment the next line if you uncomment anything in the section
      # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks:
  app_default:
    external: true
```

```yaml
version: "3.3"
services:
  containernursery:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/usr/src/app/config
    image: ghcr.io/itsecholot/containernursery:latest
networks:
  app_default:
    external: true
```
```yaml
proxyListeningPort: 80
proxyHosts:
  - domain: dev.localhost
    containerName: dozzle-dozzle-1
    proxyHost: localhost
    proxyPort: 8080
    timeoutSeconds: 20

```
```yaml
version: "3.8"
services:
  dozzle:
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: amir20/dozzle:latest
networks:
  app_default:
    external: true
```

Can anyone try to point any issues in docker files or in config, since i tryed everything i could, without any sucess
thank you

**Comment by ItsEcholot** [comment]
We need more information from you here, please set the `CN_LOG_LEVEL` environment variable to `debug` for the ContainerNursery container and check the logs for more information about what's going wrong here.

**Comment by drgshub** [comment]
Same configuration here and I'm able to get CN to stop said container, but unable to start it. Did you find amy fix for this?

I enabled debug as well and I could clearly see all the steps involved in stopping, but after that nothing else is written in the logs when accessing the domain address.

**Comment by ItsEcholot** [comment]
> Same configuration here and I'm able to get CN to stop said container, but unable to start it. Did you find amy fix for this?
> 
> I enabled debug as well and I could clearly see all the steps involved in stopping, but after that nothing else is written in the logs when accessing the domain address.

That usually means that the traffic isn’t routed through CN in the first place. Thus CN doesn’t know when you want to access the container and can’t start it.

**Comment by drgshub** [comment]
Figured as much, but I can't find the mistake in the configuration:

```
version: "3.8"
services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
```

```
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/dockerdata/prowlarr:/config
    ports:
      - 9001:9696
    restart: unless-stopped

```
Tried using CN both with a bridge between containers and with the local IP as well, but same result.

1.
```
root@docker:/srv/dockerdata/containernursery$ cat config.yml 
proxyListeningPort: 80
proxyHosts:
  - domain: prowlarr.domain.com
    containerName: prowlarr
    displayName: Prowlarr
    proxyHost: prowlarr
    proxyPort: 9696
    timeoutSeconds: 15
    stopOnTimeoutIfCpuUsageBelow: 50
    proxyUseHttps: false
    proxyUseCustomMethod: GET
```

2.
```
root@docker:/srv/dockerdata/containernursery$ cat config.yml 
proxyListeningPort: 80
proxyHosts:
  - domain: prowlarr.domain.com
    containerName: prowlarr
    displayName: Prowlarr
    proxyHost: 192.168.0.50
    proxyPort: 9001
    timeoutSeconds: 15
    stopOnTimeoutIfCpuUsageBelow: 50
    proxyUseHttps: false
    proxyUseCustomMethod: GET
```

Am I doing something wrong here?

**Comment by drgshub** [comment]
> here?

Solved by redeploying the container using the host network.

**Comment by RikudouGoku** [comment]
> > here?
> 
> Solved by redeploying the container using the host network.

Can you show how you did it? My setup only stops the container but does not start it.

CN compose:
```
services:
    itsecholot:
        image: 'ghcr.io/itsecholot/containernursery:latest'
        volumes:
            - /mnt/user/appdata/ContainerNursery/config:/usr/src/app/config
            - /var/run/docker.sock:/var/run/docker.sock
        container_name: ContainerNursery
        ports:
            - "8120:80"  
        network_mode: host
```

CN config:
```
proxyListeningPort: 8120
proxyHosts:
  - domain: gameyfin.domain.com
    containerName: gameyfin
    displayName: gameyfin
    proxyHost: gameyfin
    proxyPort: 8080
    timeoutSeconds: 15
    stopOnTimeoutIfCpuUsageBelow: 50
```

gameyfin compose:
```
services:
  gameyfin:
    image: ghcr.io/gameyfin/gameyfin:2
    container_name: gameyfin
    restart: unless-stopped
    environment:
      APP_KEY: REDACTED
    volumes:
      - /mnt/user/appdata/gameyfin/db:/opt/gameyfin/db
      - /mnt/user/appdata/gameyfin/data:/opt/gameyfin/data
      - /mnt/user/appdata/gameyfin/logs:/opt/gameyfin/logs
      - /mnt/user/Games/library:/Library
    ports:
      - 8885:8080
networks: {}

```

Nginx proxy manager Plus:

<img width="488" height="571" alt="Image" src="https://github.com/user-attachments/assets/6989583d-d974-4a10-8238-58f3f55d1b88" />
